# paths are relative to auto_annotations

greedy_gpt3.5 : # gpt-4-0314_pairwise_vH_b5_chatml-prompt
  prompt_templates:
    with_inputs: "annotators/greedy_gpt4/chatml_b3_with_inputs.txt"
    without_inputs: "annotators/greedy_gpt4/chatml_b3_without_inputs.txt"
  fn_decoder: "openai_completions"
  decoder_kwargs:
    model_name: "gpt-3.5-turbo-0613"
    max_tokens: 250
    temperature: 0
  outputs_to_match:
    1: '(?:^|\n)Output \(a\)'
    2: '(?:^|\n)Output \(b\)'
  batch_size: 3
